DROP TABLE IF EXISTS usuario CASCADE;
DROP TABLE IF EXISTS permissao CASCADE;
DROP TABLE IF EXISTS conquista CASCADE;
DROP TABLE IF EXISTS usuario_conquista CASCADE;
DROP TABLE IF EXISTS habito CASCADE;
DROP TABLE IF EXISTS diaria CASCADE;
DROP TABLE IF EXISTS afazer CASCADE;
DROP TABLE IF EXISTS missao_habito CASCADE;
DROP TABLE IF EXISTS missao_afazer CASCADE;
DROP TABLE IF EXISTS missao_diaria CASCADE;
DROP TABLE IF EXISTS dia CASCADE;
DROP TABLE IF EXISTS diaria_dia CASCADE;
DROP TABLE IF EXISTS cosmetico CASCADE;
DROP TABLE IF EXISTS cosmetico_usuario CASCADE;
DROP TABLE IF EXISTS notificacao CASCADE;
DROP TABLE IF EXISTS token_recuperar_senha CASCADE;

CREATE TABLE usuario (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	nome_completo VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL,
	imagem_perfil VARCHAR(512),
	senha VARCHAR(128),
	ativo BOOLEAN NOT NULL,
	experiencia INT NOT NULL DEFAULT 0,
	taskcoin INT NOT NULL DEFAULT 0,
	notificacoes_email BOOLEAN NOT NULL DEFAULT true,

	provider VARCHAR(15) NOT NULL,
	
	CONSTRAINT pk_usuario PRIMARY KEY (id),
	CONSTRAINT ck_provider CHECK (provider in ('LOCAL', 'GOOGLE')),
	CONSTRAINT uk_usuario_email UNIQUE (email)
);

CREATE TABLE permissao (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	funcao VARCHAR(100) NOT NULL,
	usuario_id BIGINT NOT NULL,

	CONSTRAINT pk_permissao PRIMARY KEY (id),
	CONSTRAINT uk_permissao UNIQUE (funcao, usuario_id),
	CONSTRAINT fk_permissao_usuario FOREIGN KEY (usuario_id) REFERENCES usuario (id)
);

CREATE TABLE conquista (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	nome VARCHAR(100) NOT NULL,
	descricao VARCHAR(255) NOT NULL,
	objetivo INT NOT NULL,
	tipo VARCHAR(18) NOT NULL,
	dificuldade VARCHAR(7) NOT NULL,
	
	CONSTRAINT pk_conquista PRIMARY KEY (id),
	CONSTRAINT ck_conquista_dificuldade CHECK (dificuldade in ('FACIL', 'MEDIO', 'DIFICIL')),
	CONSTRAINT ck_conquista_tipo CHECK (tipo in
	('REALIZAR_HABITOS', 'REALIZAR_DIARIAS', 'FINALIZAR_AFAZERES','REALIZAR_MISSAO',
	 'INCLUIR_HABITOS', 'INCLUIR_DIARIAS', 'INCLUIR_AFAZERES','COMPRAR_COSMETICO'))
);

CREATE TABLE usuario_conquista (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	usuario_id BIGINT NOT NULL,
	conquista_id BIGINT NOT NULL,
	progresso INT NOT NULL DEFAULT 0,
	concluida BOOLEAN NOT NULL DEFAULT false,

	CONSTRAINT pk_usuario_conquista PRIMARY KEY (id),
	CONSTRAINT fk_usuario_conquista_usuario FOREIGN KEY (usuario_id) REFERENCES usuario (id),
	CONSTRAINT fk_usuario_conquista_conquista FOREIGN KEY (conquista_id) REFERENCES conquista (id)
);

CREATE TABLE habito (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	usuario_id BIGINT NOT NULL,
	nome VARCHAR(100) NOT NULL,
	descricao VARCHAR(255) NOT NULL,
	execucoes INT NOT NULL DEFAULT 0,
	dificuldade VARCHAR(7) NOT NULL,
	ativo BOOLEAN NOT NULL,

	CONSTRAINT pk_habito PRIMARY KEY (id),
	CONSTRAINT ck_habito_dificuldade CHECK (dificuldade in ('FACIL', 'MEDIO', 'DIFICIL')),
	CONSTRAINT fk_habito_usuario FOREIGN KEY (usuario_id) REFERENCES usuario (id)
);

CREATE TABLE afazer (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	usuario_id BIGINT NOT NULL,
	nome VARCHAR(100) NOT NULL,
	descricao VARCHAR(255) NOT NULL,
	finalizado BOOLEAN NOT NULL DEFAULT false,
	dificuldade VARCHAR(7) NOT NULL,
	ativo BOOLEAN NOT NULL,
	evento_google_calendar_id VARCHAR(50),

	CONSTRAINT pk_afazer PRIMARY KEY (id),
	CONSTRAINT ck_afazer_dificuldade CHECK (dificuldade in ('FACIL', 'MEDIO', 'DIFICIL')),
	CONSTRAINT fk_afazer_usuario FOREIGN KEY (usuario_id) REFERENCES usuario (id)
);

CREATE TABLE diaria (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	usuario_id BIGINT NOT NULL,
	nome VARCHAR(100) NOT NULL,
	descricao VARCHAR(200) NOT NULL,
	hora TIME NOT NULL,
	finalizado BOOLEAN NOT NULL DEFAULT false,
	dificuldade VARCHAR(7) NOT NULL,
	ativo BOOLEAN NOT NULL,
	evento_google_calendar_id VARCHAR(50),

	CONSTRAINT pk_diaria PRIMARY KEY (id),
	CONSTRAINT ck_diaria_dificuldade CHECK (dificuldade in ('FACIL', 'MEDIO', 'DIFICIL')),
	CONSTRAINT fk_diaria_usuario FOREIGN KEY (usuario_id) REFERENCES usuario (id)
);

CREATE TABLE dia (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	nome VARCHAR(20) NOT NULL,

	CONSTRAINT pk_dia PRIMARY KEY (id)
);

CREATE TABLE diaria_dia (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	dia_id BIGINT NOT NULL,
	diaria_id BIGINT NOT NULL,

	CONSTRAINT pk_diaria_dia PRIMARY KEY (id),
	CONSTRAINT fk_diaria_dia_diaria FOREIGN KEY (diaria_id) REFERENCES diaria (id),
	CONSTRAINT fk_diaria_dia_dia FOREIGN KEY (dia_id) REFERENCES dia (id)
);

CREATE TABLE cosmetico (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	nome VARCHAR(128) NOT NULL,
	tipo VARCHAR(128) NOT NULL,
	valor INT NOT NULL,

	CONSTRAINT pk_cosmetico PRIMARY KEY (id),
	CONSTRAINT ck_cosmetico_tipo CHECK (tipo in ('ROUPA', 'PET', 'CENARIO', 'PLANTA'))
);

CREATE TABLE cosmetico_usuario (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	cosmetico_id BIGINT NOT NULL,
	usuario_id BIGINT NOT NULL,
	equipado BOOLEAN NOT NULL DEFAULT false,

	CONSTRAINT pk_cosmetico_usuario PRIMARY KEY (id),
	CONSTRAINT fk_cosmetico_usuario_usuario FOREIGN KEY (usuario_id) REFERENCES usuario (id),
	CONSTRAINT fk_cosmetico_usuario_cosmetico FOREIGN KEY (cosmetico_id) REFERENCES cosmetico (id)
);

CREATE TABLE notificacao (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	usuario_id BIGINT NOT NULL,
	titulo VARCHAR(100) NOT NULL,
	texto VARCHAR(255) NOT NULL,
	ativo BOOLEAN NOT NULL,

	CONSTRAINT pk_notificacao PRIMARY KEY (id),
	CONSTRAINT fk_notificacao_usuario FOREIGN KEY (usuario_id) REFERENCES usuario (id)
);

CREATE TABLE missao_habito (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	nome VARCHAR(100) NOT NULL,
	descricao VARCHAR(255) NOT NULL,
	usuario_id BIGINT NOT NULL,
	habito_id BIGINT NOT NULL,
	concluida BOOLEAN NOT NULL DEFAULT false,
	execucoes_necessarias INT NOT NULL,
	
	CONSTRAINT pk_missao_habito PRIMARY KEY (id),
	CONSTRAINT fk_missao_habito_usuario FOREIGN KEY (usuario_id) REFERENCES usuario (id),
	CONSTRAINT fk_missao_habito_habito FOREIGN KEY (habito_id) REFERENCES habito (id)
);

CREATE TABLE missao_diaria (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	nome VARCHAR(100) NOT NULL,
	descricao VARCHAR(255) NOT NULL,
	usuario_id BIGINT NOT NULL,
	concluida BOOLEAN NOT NULL DEFAULT false,
	diaria_id BIGINT NOT NULL,
	
	CONSTRAINT pk_missao_diaria PRIMARY KEY (id),
	CONSTRAINT fk_missao_diaria_usuario FOREIGN KEY (usuario_id) REFERENCES usuario (id),
	CONSTRAINT fk_missao_diaria_diaria FOREIGN KEY (diaria_id) REFERENCES diaria (id)
);

CREATE TABLE missao_afazer (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	nome VARCHAR(100) NOT NULL,
	descricao VARCHAR(255) NOT NULL,
	usuario_id BIGINT NOT NULL,
	concluida BOOLEAN NOT NULL DEFAULT false,
	afazer_id BIGINT NOT NULL,
	
	CONSTRAINT pk_missao_afazer PRIMARY KEY (id),
	CONSTRAINT fk_missao_afazer_usuario FOREIGN KEY (usuario_id) REFERENCES usuario (id),
	CONSTRAINT fk_missao_afazer_afazer FOREIGN KEY (afazer_id) REFERENCES afazer (id)
);
select * from usuario;
INSERT INTO dia (nome)
VALUES
('SEGUNDA'),
('TERCA'),
('QUARTA'),
('QUINTA'),
('SEXTA'),
('SABADO'),
('DOMINGO');

INSERT INTO cosmetico (nome, tipo, valor)
VALUES
('Girassol', 'PLANTA', 35),
('Folhagem1', 'PLANTA', 5),
('Folhagem2', 'PLANTA', 10),
('Folhagem3', 'PLANTA', 8),
('Folhagem4', 'PLANTA', 15),
('Folhagem5', 'PLANTA', 15),
('FloresColoridas', 'PLANTA', 25),
('Cacto', 'PLANTA', 25),
('Cogumelos', 'PLANTA', 25),
('Pinheiro', 'PLANTA', 50),
('Gato1', 'PET', 50),
('Gato2', 'PET', 50),
('Gato3', 'PET', 50),
('Cachorro1', 'PET', 50),
('Cachorro2', 'PET', 50),
('Cachorro3', 'PET', 50),
('Cachorro4', 'PET', 50),
('Cachorro5', 'PET', 50),
('Coelho', 'PET', 75),
('Alce', 'PET', 100),
('HomemCasual', 'ROUPA', 0),
('HomemCrescer', 'ROUPA', 5),
('HomemJogador', 'ROUPA', 25),
('HomemPijama', 'ROUPA', 40),
('HomemFormal', 'ROUPA', 50),
('HomemNatal', 'ROUPA', 50),
('HomemRanger', 'ROUPA', 100),
('HomemSombrio', 'ROUPA', 100),
('HomemTreinador', 'ROUPA', 100),
('HomemAventureiro', 'ROUPA', 100),
('MulherCasual', 'ROUPA', 0),
('MulherCrescer', 'ROUPA', 5),
('MulherVestido', 'ROUPA', 25),
('MulherPijama', 'ROUPA', 40),
('MulherFormal', 'ROUPA', 50),
('MulherNatal', 'ROUPA', 50),
('MulherJujuba', 'ROUPA', 100),
('MulherRanger', 'ROUPA', 100),
('MulherSombria', 'ROUPA', 100),
('MulherTreinadora', 'ROUPA', 100),
('Sala1', 'CENARIO', 0),
('Sala2', 'CENARIO', 100),
('Quarto1', 'CENARIO', 100),
('Quarto2', 'CENARIO', 100),
('Acampamento', 'CENARIO', 100),
('Biblioteca', 'CENARIO', 100),
('Escola', 'CENARIO', 100),
('Fazenda', 'CENARIO', 100),
('Natal', 'CENARIO', 100),
('Teatro', 'CENARIO', 100);
select * from usuario;
INSERT INTO conquista(nome, descricao, objetivo, tipo, dificuldade)
VALUES
('Criador de Hábitos', 'Crie 5 hábitos', 5, 'INCLUIR_HABITOS', 'FACIL'),
('Desenvolvedor de Hábitos', 'Crie 15 hábitos', 15, 'INCLUIR_HABITOS', 'MEDIO'),
('Deus dos Hábitos', 'Crie 30 hábitos', 30, 'INCLUIR_HABITOS', 'DIFICIL'),
('Criador de Diárias', 'Crie 5 diárias', 5, 'INCLUIR_DIARIAS', 'FACIL'),
('Desenvolvedor de Diárias', 'Crie 15 diárias', 15, 'INCLUIR_DIARIAS', 'MEDIO'),
('Deus das Diárias', 'Crie 30 diárias', 30, 'INCLUIR_DIARIAS', 'DIFICIL'),
('Criador de Afazeres', 'Crie 5 afazeres', 5, 'INCLUIR_AFAZERES', 'FACIL'),
('Desenvolvedor de Afazeres', 'Crie 15 afazeres', 15, 'INCLUIR_AFAZERES', 'MEDIO'),
('Deus dos Afazeres', 'Crie 30 afazeres', 30, 'INCLUIR_AFAZERES', 'DIFICIL'),

('Iniciante dos Hábitos', 'Realize 15 vezes algum hábitos', 15, 'REALIZAR_HABITOS', 'FACIL'),
('Amante dos Hábitos', 'Realize 50 vezes algum hábitos', 50, 'REALIZAR_HABITOS', 'MEDIO'),
('Rei dos Hábitos', 'Realize 100 vezes algum hábitos', 100, 'REALIZAR_HABITOS', 'DIFICIL'),
('Iniciante das Diárias', 'Realize 10 diárias', 10, 'REALIZAR_DIARIAS', 'FACIL'),
('Amante das Diárias', 'Realize 25 diárias', 25, 'REALIZAR_DIARIAS', 'MEDIO'),
('Rei das Diárias', 'Realize 50 diárias', 50, 'REALIZAR_DIARIAS', 'DIFICIL'),
('Iniciante dos Afazeres', 'Realize 10 afazeres', 10, 'FINALIZAR_AFAZERES', 'FACIL'),
('Amante dos Afazeres', 'Realize 25 afazeres', 25, 'FINALIZAR_AFAZERES', 'MEDIO'),
('Rei dos Afazeres', 'Realize 50 afazeres', 50, 'FINALIZAR_AFAZERES', 'DIFICIL'),

('Atarefado', 'Realize 3 missões diárias', 3, 'REALIZAR_MISSAO', 'FACIL'),
('Determinado', 'Realize 12 missões diárias', 12, 'REALIZAR_MISSAO', 'MEDIO'),
('Agente Especial', 'Realize 30 missões diárias', 30, 'REALIZAR_MISSAO', 'DIFICIL'),

('Novo cliente', 'Compre 1 cosméticos', 1, 'COMPRAR_COSMETICO', 'FACIL'),
('Colecionador', 'Compre 5 cosméticos', 5, 'COMPRAR_COSMETICO', 'MEDIO'),
('Milionário', 'Compre 15 cosméticos', 15, 'COMPRAR_COSMETICO', 'DIFICIL');
