package br.com.cwi.crescer.api.domain;

public enum TipoConquista {
    REALIZAR_HABITOS, INCLUIR_HABITOS,
    REALIZAR_DIARIAS, INCLUIR_DIARIAS,
    FINALIZAR_AFAZERES, INCLUIR_AFAZERES,
    COMPRAR_COSMETICO, REALIZAR_MISSAO
}
